Repository pods-framework/pods, pull requests merged in 2018-06, with the labels that each got.

#4947 `get_current_screen()` may not always be defined, even if `is_admin()` is true
  classes/PodsInit.php
Labels: Ready for merge, in progress

#4946 Always enqueue DFV on any post type edit
  classes/PodsInit.php
Labels: Ready for merge, in progress

#4954 Add tooltip for the `Hierarchical` option for taxonomies
  classes/PodsAdmin.php
Labels: Ready for review, in progress

#4971 Fix false check for file uploads directory check when exporting
  classes/PodsMigrate.php
Labels: Bug, Ready for review, in progress

#4959 '00:00:00' is midnight and a perfectly valid time value
  classes/fields/time.php
Labels: Ready for merge, in progress

#4953 Bypass `session_start()` if a valid user is logged in
  includes/general.php
Labels: Ready for merge, in progress

#4819 Update phpcs.xml.dist for WP 4.5 and PHP 5.3
  phpcs.xml.dist
Labels: Ready for merge

#4820 Update phpcs.xml.dist with prefix and textdomain
  phpcs.xml.dist
Labels: Ready for merge

#4975 PHP Codesniffer audit script
  .gitignore
  bin/phpcs-audit.sh
  bin/phpcs-autofix.sh
  phpcs.xml.dist
Labels: Ready for review, in progress

#4973 Code Editor for Pods Template double-escapes HTML when Visual Editor is OFF in WordPress
  components/Templates/includes/element-view_template.php
Labels: Ready for merge, in progress

#4978 Refactor logic for determining whether or not to activate AJAX mode for autocomplete based field views
  classes/fields/pick.php
Labels: Ready for merge, in progress

#4990 Labels: Check for localized 'help' before adding tooltip
  ui/fields/_label.php
Labels: Ready for merge, in progress

#4991 CLI: Fix missing negation on valid & exists checks
  classes/cli/Pods_CLI_Command.php
Labels: Ready for merge, in progress

#4998 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Ready for merge, in progress

#4997 JS: jQuery.fn.size() is deprecated
  ui/js/jquery.pods.attach.js
Labels: Compatibility/Deprecation, Ready for merge, in progress

#4996 PHPCS: Contents of `@since` and `@deprecated` tags
  classes/Pods.php
  classes/PodsAPI.php
  classes/PodsAdmin.php
  classes/PodsArray.php
  classes/PodsComponent.php
  classes/PodsComponents.php
  classes/PodsData.php
  classes/PodsField.php
  classes/PodsForm.php
  classes/PodsI18n.php
  classes/PodsMeta.php
  classes/PodsMigrate.php
  classes/PodsRESTHandlers.php
  classes/PodsUI.php
  classes/PodsView.php
  classes/fields/currency.php
  classes/fields/datetime.php
  classes/fields/file.php
  classes/fields/link.php
  classes/fields/number.php
  classes/fields/oembed.php
  classes/fields/pick.php
  classes/fields/time.php
  classes/fields/website.php
  components/Advanced-Relationships.php
  components/Helpers.php
  components/I18n/I18n.php
  components/Migrate-CPTUI/Migrate-CPTUI.php
  components/Migrate-Packages/Migrate-Packages.php
  components/Pages.php
  components/Roles/Roles.php
  components/Templates/Templates.php
  components/Templates/includes/functions-view_template.php
  deprecated/classes/Pods.php
  deprecated/classes/PodsAPI.php
  deprecated/deprecated.php
  includes/classes.php
  includes/data.php
  includes/general.php
  includes/media.php
  tests/phpunit/includes/_tests-integration-pods.php
  tests/phpunit/includes/tests-pods-api.php
  tests/phpunit/includes/tests-pods.php
  tests/phpunit/includes/tests-shortcodes.php
  ui/admin/form.php
  ui/admin/setup-edit.php
Labels: Ready for merge, in progress

#4994 Refactor PodsField_Pick::can_ajax()
  classes/fields/pick.php
Labels: Clean up / refactor, Ready for merge, in progress

#4916 Changelog for 2.7.4
  readme.txt
Labels: in progress

#5006 Only flush rewrite rules in an admin context
  classes/PodsInit.php
Labels: Bug, in progress

#5004 Update SelectWoo to 1.0.2
  classes/PodsInit.php
  ui/js/selectWoo/selectWoo.full.js
  ui/js/selectWoo/selectWoo.full.min.js
  ui/js/selectWoo/selectWoo.js
  ui/js/selectWoo/selectWoo.min.js
Labels: Ready for merge, in progress

#5002 Changelog for 2.7.5
  readme.txt
Labels: in progress

#5017 Records added modally via DFV's 'Add New' were not being selected
  classes/fields/pick.php
Labels: in progress

#5009 Changelog for 2.7.6
  readme.txt
Labels: in progress

#5018 Pods 2.7.6
  README.md
  classes/fields/pick.php
  init.php
  package.json
  readme.txt
Labels: in progress

#5033 Non-internationalized string "Add Another Custom Capability"
  components/Roles/ui/edit.php
Labels: Focus: i18n, Status: Ready for merge, Type: Bug

#5024 Override the `is_empty()` method on the time field
  classes/fields/time.php
Labels: Status: Ready for review, Type: Bug

#5023 In-line the textarea content for Pods Templates to avoid leading and trailing whitespace
  components/Templates/includes/element-view_template.php
Labels: Status: Ready for review, Type: Bug

#5015 PHPCS: Fix Squiz.PHP.DisallowMultipleAssignments
  classes/PodsAPI.php
  classes/PodsData.php
  classes/PodsForm.php
  classes/PodsInit.php
  classes/PodsMeta.php
  classes/PodsUI.php
  classes/PodsView.php
  components/Migrate-Packages/Migrate-Packages.php
  components/Roles/Roles.php
  components/Templates/includes/functions-view_template.php
  deprecated/classes/Pods.php
  deprecated/list_filters.php
  includes/data.php
  includes/general.php
  includes/media.php
  sql/update-2.0-beta.php
  sql/upgrade/PodsUpgrade.php
  tests/phpunit/includes/testcase.php
  tests/phpunit/includes/tests-traversal.php
  ui/admin/setup-edit-field-fluid.php
  ui/fields/date.php
  ui/fields/datetime.php
  ui/fields/slider.php
  ui/fields/time.php
Labels: Status: Ready for merge, Type: Code Standards

#5027 PHPCS: Fix WordPress.WhiteSpace.PrecisionAlignment
  classes/PodsAPI.php
  classes/PodsMigrate.php
  classes/PodsUI.php
  classes/PodsView.php
  components/Roles/ui/edit.php
  sql/update-2.0-beta.php
  ui/admin/form.php
  ui/admin/shortcode.php
  ui/admin/view.php
  ui/fields/attachment.php
  ui/fields/slider.php
  ui/front/form.php
Labels: Status: Ready for merge, Type: Code Standards

#5034 Fix "Export all" button for ACTs
  classes/PodsUI.php
Labels: Status: PR Ready, Type: Bug

#5011 Feature/4992 interpolated hook names
  classes/Pods.php
  classes/PodsAPI.php
  classes/PodsAdmin.php
  classes/PodsComponents.php
  classes/PodsForm.php
  classes/PodsInit.php
  classes/PodsMeta.php
  classes/PodsUI.php
  classes/PodsView.php
  classes/fields/code.php
  classes/fields/file.php
  classes/fields/pick.php
  classes/fields/wysiwyg.php
  components/Advanced-Relationships.php
  components/Helpers.php
  components/Templates/Templates.php
  includes/data.php
  ui/admin/form.php
  ui/admin/setup-edit.php
Labels: Status: PR Ready, Type: Code Standards

#5044 Fix 'others' capability checks for current_user_can in PodsUI
  classes/PodsUI.php
Labels: Status: PR Ready, Type: Bug
