Repository pods-framework/pods, pull requests merged in 2018-11, with the labels that each got.

#5201 Relationship field - bidirectional label
  ui/admin/setup-edit-field.php
  ui/js/jquery.pods.js
Labels: Component: UI, Status: PR Ready, Type: Enhancement

#5207 Fix issue with pods tableless access to components
  classes/PodsComponents.php
Labels: Status: PR Review, Type: Bug

#5155 Use branch relative linking for md file in readme
  README.md
Labels: Status: PR Ready, Type: Enhancement

#5180 Pods Help page: swap old forum feed with wordpress.org feed, fix warnings from SimplePie/PHP 7+
  ui/admin/help.php
  ui/styles/dist/pods-form.css
  ui/styles/dist/pods.css
  ui/styles/src/base/_admin.scss
  ui/styles/src/sourcemaps/pods-form.css.map
  ui/styles/src/sourcemaps/pods.css.map
Labels: Focus: Deprecation, Keyword: Forums, Status: PR Ready, Type: Support

#5211 Use `pods_v` to prevent PHP Warning
  includes/data.php
Labels: Status: PR Review, Type: Bug

#5145 Frontend forms conditional logic v2
  ui/front/form.php
  ui/js/jquery.pods.js
Labels: Component: Frontend Forms, Type: Enhancement
