Repository pods-framework/pods, pull requests merged in 2018-08, with the labels that each got.

#5092 Add support for Pods::field() 'keyed' argument
  classes/Pods.php
Labels: Status: PR Review

#5083 Add pods_shortcode_output filter
  includes/general.php
Labels: Keyword: Focus, Status: PR Review, Type: Enhancement

#5064 i18n: Fix compat issue with `get_current_screen()`
  classes/PodsI18n.php
Labels: Focus: Other Compatibility, Focus: i18n, Status: PR Review, Type: Bug

#5082 Changelog for 2.7.9
  readme.txt
Labels: Type: Release

#5095 Pods 2.7.9
  README.md
  classes/Pods.php
  classes/PodsI18n.php
  includes/general.php
  init.php
  package.json
  readme.txt
Labels: Type: Release

#5108 Encapsulate React and ReactDOM.
  rollup.config.js
Labels: Status: PR Review, Type: Tools

#5110 Feature/5109 dfv multiple renderers
  ui/js/pods-dfv/_src/core/renderers/mn-renderer.js
  ui/js/pods-dfv/_src/core/renderers/react-renderer.js
  ui/js/pods-dfv/_src/pods-dfv.js
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/pods-dfv.min.js.map
Labels: Component: DFV, Status: PR Review, Type: Feature

#5116 Use minified versions of Backbone.Marionette and Backbone.Radio
  classes/PodsInit.php
  ui/js/marionette/backbone.radio.min.js
  ui/js/marionette/backbone.radio.min.js.map
Labels: Component: DFV, Status: PR Review, Type: Bug

#5114 Always enqueue the DFV script by default if in the admin
  classes/PodsAdmin.php
Labels: Component: DFV, Status: PR Review, Type: Bug

#5121 Update build tool configurations in prep for 2.8
  rollup.config.js
Labels: Component: DFV, Type: Tools

#5137 Frontend forms conditional logic
  ui/front/form.php
  ui/js/jquery.pods.js
Labels: Component: Frontend Forms, Status: In progress, Type: Enhancement
