Repository pods-framework/pods, pull requests merged in 2018-04, with the labels that each got.

#4818 mockery 1.0 requires php >=5.6.0; downgrade to 0.9 for now
  composer.json
Labels: BLOCKER, Ready for merge, Unit Testing, in progress

#4742 Fixed printing numbers having more than 6 decimals with sprintf. #4741
  classes/fields/number.php
Labels: Needs Changelog, Ready for merge

#4816 Added HTML class filters for feature/4813-form-html-classes
  readme.txt
  ui/front/form.php
  ui/front/view.php
Labels: Enhancement, Ready for review

#4615 Prefix all styles with `form.pods-manage`
  ui/styles/dist/pods-form.css
  ui/styles/dist/pods-wizard.css
  ui/styles/dist/pods.css
  ui/styles/src/base/_manage.scss
  ui/styles/src/sourcemaps/pods-form.css.map
  ui/styles/src/sourcemaps/pods-wizard.css.map
  ui/styles/src/sourcemaps/pods.css.map
Labels: CSS, Needs Changelog, UI, in progress

#4632 Feature/4612 prefix css various
  ui/styles/dist/pods.css
  ui/styles/src/base/_advanced.scss
  ui/styles/src/pods.scss
  ui/styles/src/sourcemaps/pods.css.map
Labels: CSS, Needs Changelog, in progress

#4633 CSS updates/optimizations for cleditor
  ui/images/toolbar.gif
  ui/styles/dist/pods.css
  ui/styles/src/overrides/_jquery-cleditor.scss
  ui/styles/src/sourcemaps/pods.css.map
Labels: CSS, Needs Changelog, Pulled for Review, in progress

#4831 Fixes overlapping fields issue when content length is longer than normal
  ui/styles/dist/pods.css
  ui/styles/src/base/_admin.scss
  ui/styles/src/overrides/_select-woo.scss
  ui/styles/src/pods.scss
Labels: Needs Changelog, in progress

#4609 Update Pods Add New screen for extended taxonomies, the storage type is weird
  classes/PodsAPI.php
  ui/admin/setup-add.php
Labels: Patch, in progress

#4834 Create container for qTip tooltips
  includes/general.php
  ui/js/jquery.pods.js
  ui/js/qtip.js
  ui/styles/dist/pods-form.css
  ui/styles/dist/pods.css
  ui/styles/src/overrides/_jquery-qtip.scss
  ui/styles/src/pods-form.scss
  ui/styles/src/pods.scss
  ui/styles/src/sourcemaps/pods.css.map
Labels: Needs Changelog, in progress

#4837 Normalize indentation in CSS source files
  ui/styles/src/base/_admin.scss
  ui/styles/src/base/_advanced.scss
  ui/styles/src/base/_form.scss
  ui/styles/src/base/_manage.scss
  ui/styles/src/base/_meta-boxes.scss
  ui/styles/src/base/_ui-list-table.scss
  ui/styles/src/base/_wizard.scss
  ui/styles/src/helpers/_mixins.scss
  ui/styles/src/helpers/_typography.scss
  ui/styles/src/libs/_jquery-qtip.scss
  ui/styles/src/libs/_jquery-ui-custom.scss
  ui/styles/src/overrides/_codemirror.scss
  ui/styles/src/overrides/_jquery-ui-timepicker.scss
  ui/styles/src/overrides/_select-woo.scss
  ui/styles/src/pods-form.scss
  ui/styles/src/pods-wizard.scss
  ui/styles/src/pods.scss
  ui/styles/src/sourcemaps/pods-form.css.map
  ui/styles/src/sourcemaps/pods-wizard.css.map
  ui/styles/src/sourcemaps/pods.css.map
Labels: Ready for review, in progress

#4830 Currency field: Make sure decimals are empty before applying zero handling + option to add spaces between currency sign and value
  classes/fields/currency.php
  tests/phpunit/includes/tests-pods-field-currency.php
Labels: Bug, Fixed / Needs Testing, Needs Changelog, Patch, Ready for merge, in progress

#4826 Move DFV initialization into the `PodsDFV` object and no longer a jQuery plugin
  classes/PodsMeta.php
  ui/js/jquery.pods.js
  ui/js/pods-dfv/_src/pods-dfv-init.js
  ui/js/pods-dfv/_src/pods-dfv.js
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/pods-dfv.min.js.map
Labels: Needs Changelog, Ready for merge, in progress

#4714 Enhance currency field UI
  ui/fields/currency.php
  ui/styles/dist/pods-form.css
  ui/styles/src/base/_form.scss
  ui/styles/src/sourcemaps/pods-form.css.map
Labels: Needs Developer Feedback, UI, in progress

#4851 Qtip init was registered but not enqueued in certain cases
  includes/general.php
Labels: Needs Changelog, in progress
