Repository pods-framework/pods, pull requests merged in 2018-12, with the labels that each got.

#5217 Patch TinyMCE bug with Gutenberg
  ui/js/pods-dfv/_src/pods-dfv.js
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/pods-dfv.min.js.map
Labels: Focus: Other Compatibility, Status: QA pass, Type: Bug

#5164 #4961 - Fix read-only not having any effect on checkbox fields
  ui/fields/checkbox.php
Labels: Status: In progress, Status: QA pass, Type: Bug

#5220 List view scrollbar fixes
  classes/fields/pick.php
  tests/js/pods-dfv/file-upload/models/relationship-model.js
  tests/js/pods-dfv/pick/pick-spec.js
  ui/js/pods-dfv/_src/core/gb-modal-listener.js
  ui/js/pods-dfv/_src/pick/pick.js
  ui/js/pods-dfv/_src/pick/relationship-model.js
  ui/js/pods-dfv/_src/pick/views/list-item.html
  ui/js/pods-dfv/_src/pick/views/select-view.js
  ui/js/pods-dfv/_src/pods-dfv.js
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/pods-dfv.min.js.map
Labels: Status: PR Ready, Status: QA pass, Type: Bug

#5212 Modal support for Gutenberg
  ui/js/pods-dfv/_src/pods-dfv.js
  ui/js/pods-dfv/pods-dfv.min.js.map
Labels: Focus: Other Compatibility, Status: PR Review, Status: QA pass, Type: Bug

#5222 Fix component header parsing for developer/tableless mode
  classes/PodsComponents.php
Labels: Status: PR Ready, Status: QA pass, Type: Bug

#5219 Fix incorrectly calculated margins for the currency symbol
  ui/fields/currency.php
  ui/styles/dist/pods-form.css
  ui/styles/src/base/_form.scss
  ui/styles/src/sourcemaps/pods-form.css.map
Labels: Component: CSS, Component: UI, Status: QA pass, Type: Bug

#5223 Adding in the five new post_type labels coming in WordPress 5.0
  classes/PodsAdmin.php
  classes/PodsInit.php
Labels: Status: QA pass, Type: Enhancement

#5118 Changelog for 2.7.10
  readme.txt
Labels: Type: Release

#5224 Pods 2.7.10
  .babelrc
  .eslintrc.json
  README.md
  classes/Pods.php
  classes/PodsAPI.php
  classes/PodsAdmin.php
  classes/PodsComponents.php
  classes/PodsInit.php
  classes/PodsMeta.php
  classes/fields/file.php
  classes/fields/pick.php
  components/Pages.php
  includes/data.php
  init.php
  package.json
  readme.txt
  rollup.config.js
  tests/js/pods-dfv/file-upload/models/relationship-model.js
  tests/js/pods-dfv/pick/pick-spec.js
  ui/admin/help.php
  ui/admin/settings-tools.php
  ui/admin/setup-edit-field.php
  ui/fields/checkbox.php
  ui/fields/currency.php
  ui/front/form.php
  ui/js/jquery.pods.js
  ui/js/marionette/backbone.radio.min.js
  ui/js/marionette/backbone.radio.min.js.map
  ui/js/pods-dfv/_src/core/gb-modal-listener.js
  ui/js/pods-dfv/_src/pick/pick.js
  ui/js/pods-dfv/_src/pick/relationship-model.js
  ui/js/pods-dfv/_src/pick/views/list-item.html
  ui/js/pods-dfv/_src/pick/views/select-view.js
  ui/js/pods-dfv/_src/pods-dfv.js
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/pods-dfv.min.js.map
  ui/styles/dist/pods-form.css
  ui/styles/dist/pods.css
  ui/styles/src/base/_admin.scss
  ui/styles/src/base/_dfv-list.scss
  ui/styles/src/base/_form.scss
  ui/styles/src/pods-form.scss
  ui/styles/src/sourcemaps/pods-form.css.map
  ui/styles/src/sourcemaps/pods.css.map
Labels: Type: Release

#5226 More robust check for `isGutenbergEditorLoaded`
  ui/js/pods-dfv/_src/pods-dfv.js
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/pods-dfv.min.js.map
Labels: Status: QA pass, Type: Bug

#5230 Avoid extra user queries when not necessary
  classes/PodsView.php
Labels: Type: Bug

#5232 Add ability to auto calculate total_found
  classes/PodsData.php
Labels: Type: Enhancement

#5227 2.7.11 changelog
  readme.txt
Labels: Type: Release

#5235 Pods 2.7.11
  Gruntfile.js
  README.md
  classes/PodsData.php
  classes/PodsView.php
  init.php
  package.json
  readme.txt
  ui/js/pods-dfv/_src/pods-dfv.js
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/pods-dfv.min.js.map
Labels: Type: Release

#5249 updatedrrrr means updated but with 4 extra Rs
  classes/PodsInit.php
Labels: Focus: i18n, Type: Bug

#5248 Clean up currency list and sort them alphabetically
  classes/fields/currency.php
Labels: Type: Enhancement

#5251 Fix table info handling in pods_serial_comma
  classes/PodsAPI.php
  includes/data.php
Labels: Type: Bug

#5252 Changelog for #5247
  readme.txt
Labels: Type: Release

#5253 Pods 2.7.12 release
  README.md
  classes/PodsAPI.php
  classes/PodsInit.php
  classes/fields/currency.php
  includes/data.php
  init.php
  package.json
  readme.txt
Labels: Type: Release
