Repository pods-framework/pods, pull requests merged in 2018-10, with the labels that each got.

#5174 Fix explode issues with comma characters
  classes/PodsAPI.php
Labels: Status: PR Review

#5178 Add current memory usage to stats
  ui/admin/settings-tools.php
Labels: Status: PR Ready, Type: Enhancement

#5127 Pods DFV list styles were missing on the front end
  ui/styles/dist/pods-form.css
  ui/styles/dist/pods.css
  ui/styles/src/base/_dfv-list.scss
  ui/styles/src/pods-form.scss
  ui/styles/src/sourcemaps/pods-form.css.map
  ui/styles/src/sourcemaps/pods.css.map
Labels: Component: CSS, Status: PR Review, Type: Bug

#5139 List View: Don't use an array for the HTML name for single select
  ui/js/pods-dfv/_src/pick/views/list-item.html
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/pods-dfv.min.js.map
Labels: Component: DFV, Status: PR Review, Type: Bug

#5149 Allow Media Library on forms in front facing pages
  classes/fields/file.php
Labels: Status: PR Review, Type: Bug
