Repository pods-framework/pods, pull requests merged in 2018-05, with the labels that each got.

#4848 Allow traversing into post_thumbnail
  classes/Pods.php
Labels: Needs Changelog, Ready for merge

#4796 Avoid printing null message in PodsUI
  classes/PodsUI.php
Labels: Ready for merge, in progress

#4871 Disable the "Add New" button for relationships when we're inside a media modal window
  ui/js/pods-dfv/_src/pods-dfv.js
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/pods-dfv.min.js.map
Labels: Needs Changelog, Ready for merge, UI

#4696 Verify current filter before applying auto templates
  components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php
Labels: Bug, Needs Changelog, Patch, Ready for merge

#4847 Allow user-meta (and other extended Pods) to work in templates
  components/Templates/includes/functions-view_template.php
Labels: Needs Changelog, in progress

#4803 Extend the condition for WPML validation exception to cover the TE
  classes/PodsAPI.php
Labels: Ready for merge, in progress

#4877 Adjust method handling for datetime/time/date format needs
  ui/fields/date.php
  ui/fields/datetime.php
  ui/fields/time.php
Labels: Needs Changelog, Ready for review, in progress

#4879 date/time container fixes
  ui/fields/date.php
  ui/fields/datetime.php
  ui/fields/time.php
  ui/styles/dist/pods.css
  ui/styles/src/pods.scss
  ui/styles/src/sourcemaps/pods.css.map
Labels: in progress

#4874 Update Readme.txt for 2.7.2 Release
  readme.txt
Labels: Patch, in progress

#4885 Fix changelog headings
  readme.txt
Labels: Bug, in progress

#4572 Add .editorconfig
  .editorconfig
  .gitattributes
Labels: Ready for merge, Tools, in progress

#4894 Formerly `extract`ed variables were in `$args`, not `$instance`
  classes/widgets/PodsWidgetField.php
  classes/widgets/PodsWidgetForm.php
  classes/widgets/PodsWidgetList.php
  classes/widgets/PodsWidgetSingle.php
  classes/widgets/PodsWidgetView.php
Labels: Bug, Ready for review

#4897 Add 'pods-compat-container' class for jquery-ui sliders
  ui/fields/slider.php
Labels: Ready for merge, Ready for review

#4900 Update list of files that should have `export-ignore`
  .gitattributes
Labels: in progress

#4904 Try/catch exception for DateTime
  classes/fields/datetime.php
Labels: Patch, Ready for review, in progress

#4905 Fix filter pods_form_html_class
  ui/front/form.php
Labels: Patch, Ready for review, in progress

#4899 Prep changelog PR for 2.7.2.1
  readme.txt
Labels: in progress

#4906 Pods 2.7.2.1
  .editorconfig
  .gitattributes
  README.md
  classes/fields/datetime.php
  classes/widgets/PodsWidgetField.php
  classes/widgets/PodsWidgetForm.php
  classes/widgets/PodsWidgetList.php
  classes/widgets/PodsWidgetSingle.php
  classes/widgets/PodsWidgetView.php
  init.php
  package.json
  readme.txt
  ui/fields/slider.php
  ui/front/form.php
Labels: in progress

#4910 Fix copy/paste mistake for `search` param in Pods shortcode
  includes/general.php
Labels: in progress

#4915 Pods 2.7.3
  README.md
  classes/widgets/PodsWidgetField.php
  classes/widgets/PodsWidgetForm.php
  classes/widgets/PodsWidgetList.php
  classes/widgets/PodsWidgetSingle.php
  classes/widgets/PodsWidgetView.php
  includes/general.php
  init.php
  package.json
  readme.txt
Labels: in progress

#4920 Check if $color has a value before checking this value.
  classes/fields/color.php
Labels: Bug, in progress

#4927 Fix CodeMirror fields in Taxonomy and User edit forms
  components/Templates/includes/element-view_template.php
  ui/fields/codemirror.php
  ui/styles/dist/pods.css
  ui/styles/src/pods.scss
  ui/styles/src/sourcemaps/pods.css.map
Labels: in progress

#4928 Multiselect predefined lists not finding the proper selected IDs
  classes/fields/pick.php
Labels: in progress

#4942 Updating Issue Template to fix #4924
  docs/issue_template.md
  docs/pull_request_template.md
Labels: Support, in progress
