Repository pods-framework/pods, pull requests merged in 2018-03, with the labels that each got.

#4779 Add WP-CLI commands
  classes/Pods.php
  classes/PodsAPI.php
  classes/PodsInit.php
  classes/PodsMigrate.php
  classes/PodsUI.php
  classes/cli/PodsAPI_CLI_Command.php
  classes/cli/Pods_CLI_Command.php
  init.php
  readme.txt
Labels: Feature, in progress

#4590 eslint rules and formatting for Javascript (DFV only)
  .eslintrc.json
  package.json
  ui/js/pods-dfv/_src/core/dfv-modal.js
  ui/js/pods-dfv/_src/core/iframe-frame.js
  ui/js/pods-dfv/_src/core/pods-field-model.js
  ui/js/pods-dfv/_src/field-manifest.js
  ui/js/pods-dfv/_src/file-upload/file-upload-model.js
  ui/js/pods-dfv/_src/file-upload/file-upload.js
  ui/js/pods-dfv/_src/file-upload/uploaders/media-modal.js
  ui/js/pods-dfv/_src/file-upload/uploaders/plupload.js
  ui/js/pods-dfv/_src/file-upload/views/file-upload-form.js
  ui/js/pods-dfv/_src/file-upload/views/file-upload-list.js
  ui/js/pods-dfv/_src/file-upload/views/file-upload-queue.js
  ui/js/pods-dfv/_src/model-manifest.js
  ui/js/pods-dfv/_src/pick/pick-field-model.js
  ui/js/pods-dfv/_src/pick/pick.js
  ui/js/pods-dfv/_src/pick/relationship-model.js
  ui/js/pods-dfv/_src/pick/views/add-new.js
  ui/js/pods-dfv/_src/pick/views/checkbox-view.js
  ui/js/pods-dfv/_src/pick/views/list-view.js
  ui/js/pods-dfv/_src/pick/views/radio-view.js
  ui/js/pods-dfv/_src/pick/views/select-view.js
  ui/js/pods-dfv/_src/pods-dfv-init.js
  ui/js/pods-dfv/_src/pods-dfv.js
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/pods-dfv.min.js.map
Labels: Patch, in progress

#4789 Skip npm install and js tests on the PHP 5.3/Precise box
  .travis.yml
Labels: in progress, ready

#4787 Simplify how we inject the PHP string into the JS
  ui/fields/number.php
Labels: in progress

#4794 Text field readonly fix
  classes/fields/text.php
Labels: in progress

#4795 Feature/4785 dfv media library grid mode
  classes/PodsInit.php
  classes/PodsMeta.php
Labels: in progress, ready

#4797 Missing thickbox styles for `PodsUI::filters()`
  classes/PodsUI.php
Labels: Ready for review, in progress

#4460 composer: composer installers v1.3-->1.4
  composer.json
Labels: Ready for merge, Unit Testing, in progress

#4792 composer/installers to 1.5
  composer.json
  package.json
Labels: Ready for merge, Unit Testing, in progress
