Repository pods-framework/pods, pull requests merged in 2019-06, with the labels that each got.

#4811 travis-ci: test with php 7.3
  .travis.yml
Labels: Status: PR > Ready For Merge

#5153 Composer: WP Coding Standards 1.1
  composer.json
Labels: Type: Code Standards

#5182 session_id conditional never checked for tcp sessions
  includes/general.php
Labels: Status: PR > QA pass, Type: Bug

#5062 Fix PodsData fetch for when using object cache and settings pages (possibly other types too)
  classes/PodsData.php
Labels: Status: PR > QA pass, Type: Bug

#5205 Fix foreach check_value loop by checking first if it is an array
  classes/fields/pick.php
Labels: Status: PR > QA pass, Type: Bug

#5390 Fix ACT table charset
  classes/PodsAPI.php
Labels: Status: PR > QA pass, Type: Bug

#5363 Remove floats from fields within pods manage fields
  ui/styles/dist/pods.css
  ui/styles/src/base/_admin.scss
  ui/styles/src/sourcemaps/pods.css.map
Labels: Component: CSS, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5377 Added Nigerian Naira to PODs
  classes/fields/currency.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5388 Fix typo `width` > `with`
  classes/fields/currency.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5302 DateTime/Time field enhancements
  classes/fields/datetime.php
  classes/fields/time.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Code Standards

#5358 Use `Marionette.noConflict()` to keep a private copy of Marionette
  classes/PodsInit.php
  tests/js/pods-dfv/_setup.js
  ui/js/pods-dfv/_src/core/dfv-modal.js
  ui/js/pods-dfv/_src/core/iframe-frame.js
  ui/js/pods-dfv/_src/core/pods-field-model.js
  ui/js/pods-dfv/_src/core/pods-field-views.js
  ui/js/pods-dfv/_src/file-upload/file-upload-model.js
  ui/js/pods-dfv/_src/file-upload/file-upload.js
  ui/js/pods-dfv/_src/file-upload/uploaders/media-modal.js
  ui/js/pods-dfv/_src/file-upload/uploaders/plupload.js
  ui/js/pods-dfv/_src/file-upload/uploaders/pods-file-uploader.js
  ui/js/pods-dfv/_src/file-upload/views/file-upload-form.js
  ui/js/pods-dfv/_src/file-upload/views/file-upload-list.js
  ui/js/pods-dfv/_src/file-upload/views/file-upload-queue.js
  ui/js/pods-dfv/_src/pick/pick-field-model.js
  ui/js/pods-dfv/_src/pick/pick.js
  ui/js/pods-dfv/_src/pick/relationship-model.js
  ui/js/pods-dfv/_src/pick/views/add-new.js
  ui/js/pods-dfv/_src/pick/views/checkbox-view.js
  ui/js/pods-dfv/_src/pick/views/list-view.js
  ui/js/pods-dfv/_src/pick/views/radio-view.js
  ui/js/pods-dfv/_src/pick/views/select-view.js
  ui/js/pods-dfv/_src/pods-dfv.js
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/pods-dfv.min.js.map
Labels: Component: DFV, Focus: Other Compatibility, Status: PR > QA pass, Type: Bug

#5385 Update new_blog hook for `wp_insert_site`
  classes/PodsInit.php
Labels: Status: PR > QA pass, Type: Enhancement

#5395 PodsInit load error fix
  classes/PodsAPI.php
Labels: Priority: Blocker, Status: PR > QA pass, Type: Bug

#5397 Wrap shortcodes with exception handling
  classes/PodsData.php
  includes/general.php
Labels: Status: PR > QA pass, Type: Bug

#5399 Add Pods debug information to Site Info area
  classes/PodsAdmin.php
  classes/PodsInit.php
  includes/general.php
  sql/upgrade/PodsUpgrade.php
  ui/admin/settings-tools.php
Labels: Status: PR > QA pass, Type: Enhancement

#5287 2.7.13 changelog
  readme.txt
Labels: Type: Release
