Repository pods-framework/pods, pull requests merged in 2019-02, with the labels that each got.

#5275 Remove temporary workaround for #5197
  ui/js/pods-dfv/_src/pods-dfv.js
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/pods-dfv.min.js.map
Labels: Focus: Other Compatibility, Status: QA pass, Type: Bug

#5255 Do not force pick item IDs to zero
  classes/fields/pick.php
Labels: Status: PR Ready, Status: QA pending, Type: Bug

#5256 Manage Fields: avoid stripping any intentionally inserted literal HTML
  ui/admin/setup-edit-field.php
Labels: Component: UI, Status: PR Ready, Status: QA pending, Type: Bug

#5260 Pods i18n: WP 5.0 labels + compatibility with WP 4.7+ get_user_locale()
  components/I18n/I18n.php
Labels: Focus: Integration, Focus: i18n, Status: PR Ready, Status: QA pending, Type: Bug

#4768 Re Issue #3962: Make auto templates for a Taxonomy Pod behave sensibly
  components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php
  components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Settings.php
Labels: Status: In progress, Status: QA pending

#5294 Fix option cache handling when using external object cache
  classes/PodsView.php
Labels: Status: PR > Pending Code Review, Type: Bug

#5291 Phone Field: Blank values with the formatting logic. Forma…
  classes/fields/phone.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5290 Force WWW options have never worked
  classes/fields/website.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5292 Remove "2.x" prefix from the release tag
  Gruntfile.js
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug, Type: Tools

#5298 Avoid redundant transient set
  classes/PodsAPI.php
Labels: Status: PR > Ready For Merge, Type: Bug

#5297 Always use `date_i18n` to ensure proper localization.
  classes/fields/datetime.php
Labels: Focus: i18n, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5300 Support meta fields as display field for relationships
  classes/fields/pick.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge
