Repository pods-framework/pods, pull requests merged in 2019-08, with the labels that each got.

#5430 FIX Import from file with absolute path
  classes/PodsMigrate.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5418 Date/Time fields: Omit timezone to prevent conversion
  classes/fields/datetime.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5437 Allow all callables in helpers
  classes/Pods.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5428 Do not allow reserved keywords do be used for pods
  classes/PodsAPI.php
  includes/general.php
  ui/js/jquery.pods.js
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5439 Fix numeric soft format issue removing decimals & numeric slider input formatting
  classes/fields/number.php
Labels: Status: PR > QA pass, Type: Bug

#5375 Try and get single select to work with [each] templating
  components/Templates/includes/functions-view_template.php
Labels: Status: PR > QA pass, Type: Enhancement

#5453 Improve error handling in pods_error()
  classes/PodsAPI.php
  classes/PodsAdmin.php
  classes/PodsComponents.php
  classes/PodsData.php
  classes/fields/file.php
  components/Helpers.php
  includes/general.php
Labels: Priority: Blocker, Status: PR > Ready For Merge, Type: Bug
