Repository pods-framework/pods, pull requests merged in 2019-07, with the labels that each got.

#5409 Always convert with UTC timezone
  classes/fields/datetime.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5404 Pick/Select: Add new button disabled when the placeholder is selected in a dropdown
  ui/js/pods-dfv/_src/pick/views/select-view.js
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/pods-dfv.min.js.map
Labels: Status: PR > QA pending, Type: Bug

#5412 Fix undefined variable notices in PodsAPI::save_pod_item()
  classes/PodsAPI.php
Labels: Status: PR > QA pending, Type: Bug

#5414 2.7.14 changelog
  readme.txt
Labels: Type: Release

#5413 Release 2.7.14
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  classes/PodsAPI.php
  classes/fields/datetime.php
  init.php
  package.json
  readme.txt
  ui/js/pods-dfv/_src/pick/views/select-view.js
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/pods-dfv.min.js.map
Labels: Type: Release
