Repository pods-framework/pods, pull requests merged in 2019-10, with the labels that each got.

#5485 Save field data from traversed fields for formatting
  classes/Pods.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5508 Add validate method to boolean field to fix #5481
  classes/fields/boolean.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5496 Fix GravityForms integration
  components/Roles/Roles.php
Labels: Focus: Other Compatibility, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5478 Allow migrate packages import to work with reserved words
  components/Migrate-Packages/Migrate-Packages.php
  tests/phpunit/includes/Bugs/Test_5476.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5480 Fix pods_str_replace
  includes/data.php
  tests/phpunit/includes/Bugs/Test_5254.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5494 Update PHPCS rules/action
  composer.json
  phpcs.xml.dist
Labels: Type: Tests
