Repository pods-framework/pods, pull requests merged in 2019-11, with the labels that each got.

#5504 Refactor capability checks for ACT's
  classes/PodsUI.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5511 Sanitize meta values before passing to *_post_meta functions
  classes/PodsAPI.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5493 Add `object` key to prevent undefined index notice
  classes/PodsAPI.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5513 Make sure number of arguments passed to PodsMeta->save_post() is correct
  includes/general.php
Labels: Status: PR > QA pending, Status: PR > Ready For Merge, Type: Bug

#5510 Fix/Enhance ACT list view pagination
  classes/PodsUI.php
Labels: Component: UI, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5505 Fix custom table relationships SQL error
  classes/PodsAPI.php
Labels: Keyword: Needs Unit Tests, Status: PR > QA pass, Status: PR > Ready For Merge

#5507 Allow Pods to ALTER table if the SQL field definition has changed (not just name)
  classes/PodsAPI.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge

#5497 Admin menu: set hook priority to 9 instead of 99
  classes/PodsAdmin.php
Labels: Focus: Other Compatibility, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5289 Re Issue #3962: Make auto templates for a Taxonomy Pod behave sensibly
  components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php
  components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Settings.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge

#5467 Bug: jQuery date & time picker overlapping formats.
  classes/fields/date.php
  classes/fields/datetime.php
  classes/fields/time.php
  ui/fields/datetime.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5501 Fixes for WP 5.3
  classes/PodsInit.php
  ui/js/pods-dfv/_src/core/iframe-frame.js
  ui/styles/src/base/_admin.scss
  ui/styles/src/base/_form.scss
  ui/styles/src/base/_ui-list-table.scss
  ui/styles/src/libs/_jquery-qtip.scss
Labels: Keyword: Focus, Status: PR > QA pass, Status: PR > Ready For Merge

#5520 Validate query tags before default to current object
  includes/general.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5310 Avoid SQL errors when using special magic tags
  classes/PodsAdmin.php
  classes/PodsInit.php
  includes/data.php
  includes/general.php
Labels: Status: Need Dev Feedback, Status: PR > QA pass, Status: PR > Ready For Merge

#5528 DateTime: Add onClose method to always parse any manual input data
  ui/fields/datetime.php
Labels: Status: PR > QA pending, Status: PR > Ready For Merge, Type: Bug, Type: Enhancement

#5516 Add sanitize_title option to sluggables instead of applying default
  ui/admin/setup-edit-field-fluid.php
  ui/js/jquery.pods.js
Labels: Status: PR > QA pending, Status: PR > Ready For Merge, Type: Bug, Type: Enhancement

#5517 Unslash simple relationship values to support saving quoted values
  classes/PodsAPI.php
Labels: Keyword: Needs Unit Tests, Status: PR > QA pending, Status: PR > Ready For Merge, Type: Bug

#5521 2.7.16 changelog
  readme.txt
Labels: Type: Release

#5529 Pods 2.7.16
  .github/workflows/mt-code-review.yml
  .travis.yml
  Gruntfile.js
  classes/Pods.php
  classes/PodsAPI.php
  classes/PodsAdmin.php
  classes/PodsInit.php
  classes/PodsUI.php
  classes/fields/boolean.php
  classes/fields/date.php
  classes/fields/datetime.php
  classes/fields/time.php
  components/Migrate-Packages/Migrate-Packages.php
  components/Roles/Roles.php
  components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php
  components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Settings.php
  composer.json
  grunt-workflow.md
  includes/data.php
  includes/general.php
  init.php
  package.json
  phpcs.xml.dist
  readme.txt
  tests/phpunit/includes/Bugs/Test_5254.php
  tests/phpunit/includes/Bugs/Test_5476.php
  tests/phpunit/includes/testcase.php
  ui/admin/setup-edit-field-fluid.php
  ui/fields/datetime.php
  ui/js/jquery.pods.js
  ui/js/pods-dfv/_src/core/iframe-frame.js
  ui/styles/src/base/_admin.scss
  ui/styles/src/base/_form.scss
  ui/styles/src/base/_ui-list-table.scss
  ui/styles/src/libs/_jquery-qtip.scss
Labels: Type: Release

#5530 Fix removed main filter for auto templates
  components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php
Labels: Priority: Blocker, Type: Bug
