Repository pods-framework/pods, pull requests merged in 2020-03, with the labels that each got.

#5538 DateTime: Use is_empty() to centralize validation
  classes/fields/datetime.php
  ui/fields/datetime.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5560 Fix compare 9'999.99 format
  classes/fields/number.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5607 WP 5.4 Compatibility: Add user Pod fields to privacy export data
  classes/PodsInit.php
Labels: Focus: Other Compatibility, Status: PR > QA pass, Status: PR > Ready For Merge

#5608 Add poststuff class for wp5.4 compatibility
  components/Roles/ui/edit.php
  ui/admin/form.php
  ui/admin/setup-edit.php
  ui/admin/view.php
Labels: Focus: Other Compatibility, Status: PR > QA pass, Status: PR > Ready For Merge

#5041 Fixed the CLI export/export-item commands.
  classes/PodsMigrate.php
  classes/cli/Pods_CLI_Command.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5571 Add Friends of Pods callout
  classes/PodsAdmin.php
  classes/PodsInit.php
  classes/PodsUI.php
  ui/styles/dist/pods-form.css
  ui/styles/dist/pods.css
  ui/styles/src/base/_admin.scss
  ui/styles/src/sourcemaps/pods-form.css.map
  ui/styles/src/sourcemaps/pods.css.map
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5550 Allow No (0) as an answer for radio and select boolean fields
  classes/fields/boolean.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5546 Fix components meta to be compatible with get_file_data()
  components/Advanced-Content-Types.php
  components/Advanced-Relationships.php
  components/Builder/Builder.php
  components/Helpers.php
  components/I18n/I18n.php
  components/Markdown.php
  components/Migrate-CPTUI/Migrate-CPTUI.php
  components/Migrate-Packages/Migrate-Packages.php
  components/Pages.php
  components/Roles/Roles.php
  components/Table-Storage.php
  components/Templates/Templates.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5536 Add "full" to available image sizes
  classes/fields/file.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5581 Add `not_found` tag for shortcodes
  includes/general.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5583 Fix PHP 7.4 deprecation
  components/Markdown.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5558 Validate $lang_data before accessing array
  classes/PodsI18n.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5611 Enhance Friends of Pods callout
  ui/styles/dist/pods.css
  ui/styles/src/base/_admin.scss
  ui/styles/src/sourcemaps/pods.css.map
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5020 Update inline docs for pick field selected logic
  classes/fields/pick.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Inline Docs

#5541 Updated WordPress Codex Link for Gallery Documentation
  classes/fields/file.php
Labels: Type: Documentation

#5622 Fix dbx_post_advanced deprecated notices and error on page
  classes/fields/pick.php
  components/Helpers.php
  components/Pages.php
  components/Templates/Templates.php
  components/Templates/class-pods_templates.php
  components/Templates/includes/functions-pod_reference.php
Labels: Component: UI, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#4855 Add ACF backwards compatibility functions/shortcode
  classes/PodsInit.php
  includes/compatibility/acf.php
  includes/general.php
Labels: Focus: Other Compatibility, Keyword: Focus, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Feature

#5623 Add new actions when saving field during table altering
  classes/PodsAPI.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5613 Custom multi-relationship display format
  classes/fields/pick.php
  includes/data.php
Labels: Status: PR > QA pending, Status: PR > Ready For Merge, Type: Enhancement

#5617 Set type detection based on classes instead of parameters
  classes/Pods.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5610 Support post thumbnail traversal
  classes/Pods.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5628 Number/Currency: Fix default 0 value if empty
  classes/fields/currency.php
  classes/fields/number.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5629 Fix getting the post thumb by correct ID
  classes/Pods.php
Labels: Priority: Blocker, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5618 Allow midnight as time value
  classes/fields/datetime.php
Labels: Status: PR > QA pending, Status: PR > Ready For Merge, Type: Bug

#5631 Fix PHP 7.4 notices
  classes/PodsAPI.php
  classes/PodsData.php
Labels: Priority: Blocker, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5578 Fix get_meta() cache loop
  classes/PodsMeta.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5634 Fix flexbox issue with Friends of Pods callout
  classes/PodsAdmin.php
  classes/PodsUI.php
  ui/admin/help.php
  ui/admin/settings.php
  ui/styles/dist/pods.css
  ui/styles/src/base/_admin.scss
Labels: Priority: Blocker, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5635 2.7.17 changelog
  readme.txt
Labels: Type: Release

#5639 Shortcodes auto use_current fix
  includes/general.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5641 Fix pods_trim charlist
  includes/data.php
  tests/phpunit/includes/tests-pods-data.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Status: Unit Tested, Type: Bug

#5638 Fix pick display serial comma
  classes/fields/pick.php
  tests/phpunit/includes/tests-pods-data.php
  tests/phpunit/includes/tests-pods-field-boolean.php
  tests/phpunit/includes/tests-pods-field-currency.php
  tests/phpunit/includes/tests-pods-field-pick.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Status: Unit Tested, Type: Bug, Type: Enhancement

#5645 Pods 2.7.17.1
  README.md
  classes/fields/pick.php
  docs/pull_request_template.md
  includes/data.php
  includes/general.php
  init.php
  package.json
  readme.txt
  tests/phpunit/includes/tests-pods-data.php
  tests/phpunit/includes/tests-pods-field-boolean.php
  tests/phpunit/includes/tests-pods-field-currency.php
  tests/phpunit/includes/tests-pods-field-pick.php
Labels: Type: Release

#5647 Prefix Pages and Templates components with "Pod" in admin menu
  components/Pages.php
  components/Templates/Templates.php
Labels: Status: PR > QA pending, Status: PR > Ready For Merge, Type: Enhancement

#5659 Fix newer array notation
  classes/PodsAPI.php
Labels: Focus: Back Compat, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5656 Fix [if][else] magic tags for boolean fields
  classes/fields/boolean.php
  tests/phpunit/includes/tests-pods-field-boolean.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Status: Unit Tested, Type: Bug

#5653 Number/Currency: Fix parsing input in various formats
  classes/fields/currency.php
  classes/fields/number.php
  tests/phpunit/includes/tests-pods-field-currency.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Status: Unit Tested, Type: Bug

#5642 Add special magic tags tests for pods_evaluate_tags()
  includes/data.php
  tests/phpunit/includes/tests-pods-data.php
Labels: Focus: Other Compatibility, Status: PR > Ready For Merge, Status: Unit Tested, Type: Bug

#5644 Use wp_list_filter() to remove duplicate code
  includes/data.php
  tests/phpunit/includes/tests-pods-data.php
Labels: Status: PR > Ready For Merge, Status: Unit Tested, Type: Clean up / refactor
