Repository pods-framework/pods, pull requests merged in 2020-06, with the labels that each got.

#5732 Manage Groups: Add Group modal
  ui/js/blocks/pods-blocks-api.min.asset.json
  ui/js/blocks/pods-blocks-api.min.js
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-groups.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/settings-modal.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/settings-modal.scss
  ui/js/dfv/src/admin/edit-pod/store/actions.js
  ui/js/dfv/src/admin/edit-pod/store/api-middleware.js
  ui/js/dfv/src/admin/edit-pod/store/reducer.js
  ui/js/dfv/src/admin/edit-pod/store/selectors.js
  ui/js/dfv/src/admin/edit-pod/store/test/actions.js
  webpack.common.js
  webpack.dev.js
Labels: Component: React, Component: UI, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Feature

#5742 Add noopener and noreferrer for all target _blank links
  classes/PodsAdmin.php
  classes/PodsInit.php
  classes/PodsUI.php
  classes/fields/date.php
  classes/fields/datetime.php
  classes/fields/file.php
  classes/fields/link.php
  classes/fields/time.php
  classes/fields/website.php
  components/Helpers.php
  components/Pages.php
  components/Roles/Roles.php
  components/Templates/Templates.php
  includes/general.php
  ui/admin/form.php
  ui/admin/help.php
  ui/admin/setup-add.php
  ui/admin/setup-edit.php
  ui/admin/upgrade/backup.php
  ui/admin/view.php
  ui/admin/widgets/list.php
  ui/admin/widgets/single.php
  ui/js/pods-dfv/_src/file-upload/views/file-upload-item.html
  ui/js/pods-dfv/_src/pick/views/list-item.html
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5739 Manage Group Fields (Part 1)
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/dynamic-tab-content.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-groups.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-groups.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list-item.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/manage-fields.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/settings-modal.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/settings-modal.scss
  ui/js/dfv/src/admin/edit-pod/store/actions.js
  ui/js/dfv/src/admin/edit-pod/store/constants.js
  ui/js/dfv/src/admin/edit-pod/store/reducer.js
  ui/js/dfv/src/admin/edit-pod/store/selectors.js
  ui/js/dfv/src/components/dependent-field-option.js
  ui/js/dfv/src/components/field-option.js
  ui/js/dfv/src/pods-dfv.js
  ui/js/dfv/src/prop-types.js
Labels: Component: React, Component: UI, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Feature

#5745 Nested relationship fields should render as array of objects
  classes/PodsAPI.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5661 Simplify & fix parsing proper meta_value format
  classes/PodsMeta.php
  tests/phpunit/includes/Meta/Test_Metadata.php
Labels: Priority: Blocker, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5716 Fix factory in pods testcase
  tests/phpunit/includes/testcase.php
  tests/phpunit/includes/tests-pods-data.php
Labels: Component: Unit Testing, Focus: Other Compatibility, Status: PR > QA pass, Status: PR > Ready For Merge

#5682 Various Pods::field() enhancements
  classes/Pods.php
  includes/general.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Clean up / refactor

#5720 Support `get_query_var` in pods_v (and thus special magic tags)
  includes/data.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5733 Pods::process_magic_tags() enhancements
  classes/Pods.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Clean up / refactor

#5741 Fix relationship dropdown error & encoding
  classes/fields/file.php
  classes/fields/pick.php
  ui/js/pods-dfv/_src/pick/views/select-view.js
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/pods-dfv.min.js.map
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5604 Allow traversing into serialized meta/option field values
  classes/Pods.php
  includes/data.php
  tests/phpunit/includes/tests-pods-data.php
Labels: Status: Holding, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5757 Feature/5756 get object data params filter
  classes/fields/pick.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5762 2.7.21 changelog
  readme.txt
Labels: Type: Release

#5761 Pods 2.7.21
  Gruntfile.js
  classes/Pods.php
  classes/PodsAPI.php
  classes/PodsAdmin.php
  classes/PodsInit.php
  classes/PodsMeta.php
  classes/PodsUI.php
  classes/fields/date.php
  classes/fields/datetime.php
  classes/fields/file.php
  classes/fields/link.php
  classes/fields/pick.php
  classes/fields/time.php
  classes/fields/website.php
  classes/fields/wysiwyg.php
  components/Helpers.php
  components/Pages.php
  components/Roles/Roles.php
  components/Templates/Templates.php
  includes/data.php
  includes/general.php
  init.php
  package.json
  readme.txt
  tests/phpunit/includes/Meta/Test_Metadata.php
  tests/phpunit/includes/testcase.php
  tests/phpunit/includes/tests-pods-data.php
  tests/phpunit/includes/tests-pods-field-datetime.php
  ui/admin/form.php
  ui/admin/help.php
  ui/admin/setup-add.php
  ui/admin/setup-edit.php
  ui/admin/upgrade/backup.php
  ui/admin/view.php
  ui/admin/widgets/list.php
  ui/admin/widgets/single.php
  ui/fields/tinymce.php
  ui/js/pods-dfv/_src/file-upload/views/file-upload-item.html
  ui/js/pods-dfv/_src/pick/views/list-item.html
  ui/js/pods-dfv/_src/pick/views/select-view.js
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/pods-dfv.min.js.map
Labels: Type: Release
