Repository pods-framework/pods, pull requests merged in 2020-08, with the labels that each got.

#5783 Fix preview link for ACT Pods
  classes/Pods.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5791 Update Pods Form and Pods View placeholder images
  src/Pods/Blocks/Types/Form.php
  src/Pods/Blocks/Types/View.php
  ui/images/pods-form-placeholder.svg
  ui/images/pods-logo-green.svg
  ui/images/pods-view-placeholder.svg
  ui/styles/dist/pods.css
  ui/styles/src/base/_block-placeholders.scss
  ui/styles/src/pods.scss
  ui/styles/src/sourcemaps/pods.css.map
Labels: Component: Blocks API, Component: Gutenberg, Status: PR > Pending Code Review, Status: PR > QA pending, Type: Enhancement

#5800 Edit Pods QA
  ui/js/blocks/pods-blocks-api.min.asset.json
  ui/js/blocks/pods-blocks-api.min.js
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list-item.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/manage-fields.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/settings-modal.scss
  ui/js/dfv/src/admin/edit-pod/store/actions.js
  ui/js/dfv/src/admin/edit-pod/store/reducer.js
  ui/js/dfv/src/components/dependent-field-option.js
  ui/js/dfv/src/components/field-option.js
  ui/js/dfv/src/components/help-tooltip.js
  ui/js/dfv/src/components/help-tooltip.scss
  ui/js/dfv/src/prop-types.js
Labels: Component: React, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Feature

#5806 Fix DFV div issues with PodsUI filters and add .toggle-row class handling for frontend
  classes/PodsForm.php
  classes/PodsUI.php
  ui/admin/form.php
  ui/admin/postbox-header.php
  ui/admin/view.php
  ui/styles/dist/pods.css
  ui/styles/src/base/_ui-list-table.scss
  ui/styles/src/sourcemaps/pods.css.map
  vendor/freemius/wordpress-sdk/includes/fs-plugin-info-dialog.php
Labels: Component: DFV, Component: UI, Status: PR > Pending Code Review, Status: PR > QA pass, Type: Bug

#5768 pods_permission() > use maybe_unserialize()
  includes/general.php
Labels: Status: PR > QA pending, Status: PR > Ready For Merge, Type: Bug

#5779 Pods 2.7.22
  .gitattributes
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  classes/Pods.php
  classes/PodsForm.php
  classes/PodsRESTHandlers.php
  classes/PodsUI.php
  composer.json
  docs/git-workflow.md
  docs/pull_request_template.md
  docs/release-workflow.md
  git-workflow.md
  grunt-workflow.md
  includes/general.php
  init.php
  package.json
  readme.txt
  tests/performance/Pods.php
  tests/performance/_support/Factory.php
  ui/admin/form.php
  ui/admin/postbox-header.php
  ui/admin/view.php
  ui/styles/dist/pods.css
  ui/styles/src/base/_ui-list-table.scss
  ui/styles/src/sourcemaps/pods.css.map
  vendor/freemius/wordpress-sdk/includes/fs-plugin-info-dialog.php
Labels: Type: Release

#5807 Edit Pod Fields QA/Drag and drop rework
  ui/js/blocks/pods-blocks-api.min.asset.json
  ui/js/blocks/pods-blocks-api.min.js
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-groups.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list-item.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list-item.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/manage-fields.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/settings-modal.scss
  ui/js/dfv/src/admin/edit-pod/store/selectors.js
Labels: Component: React, Component: UI, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Feature

#5808 More Edit Pods QA
  ui/js/blocks/pods-blocks-api.min.asset.json
  ui/js/blocks/pods-blocks-api.min.js
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list-item.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list-item.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list.scss
  ui/js/dfv/src/admin/edit-pod/store/reducer.js
  ui/js/dfv/src/admin/edit-pod/store/state-paths.js
  ui/js/dfv/src/admin/edit-pod/store/store.js
  ui/js/dfv/src/components/field-option.js
  ui/js/dfv/src/components/help-tooltip.js
  ui/js/dfv/src/components/help-tooltip.scss
  ui/js/dfv/src/prop-types.js
  ui/styles/dist/pods.css
  ui/styles/src/base/_admin.scss
  ui/styles/src/sourcemaps/pods.css.map
Labels: Component: React, Component: UI, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Feature

#5810 Fix possible PHP warning in file.php
  classes/fields/file.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5814 Bidirectional Relationships
  src/Pods/Admin/Config/Field.php
  ui/js/blocks/pods-blocks-api.min.asset.json
  ui/js/blocks/pods-blocks-api.min.js
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/settings-modal.js
  ui/js/dfv/src/components/dependent-field-option.js
  ui/js/dfv/src/components/field-option.js
  ui/js/dfv/src/helpers/validateFieldDependencies.js
  ui/js/dfv/src/prop-types.js
Labels: Component: React, Component: UI, Status: PR > QA pass, Status: PR > Reviewed and Ready

#5818 More Edit Pod Fields QA
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list-item.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list-item.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list.js
  ui/js/dfv/src/admin/edit-pod/store/actions.js
  ui/js/dfv/src/admin/edit-pod/store/reducer.js
  ui/js/dfv/src/admin/edit-pod/store/selectors.js
  ui/js/dfv/src/admin/edit-pod/store/state-paths.js
  ui/js/dfv/src/admin/edit-pod/store/test/store.js
  ui/js/dfv/src/admin/edit-pod/store/testData.js
  ui/js/dfv/src/components/dependent-field-option.js
  ui/js/dfv/src/components/field-option.js
  ui/js/dfv/src/components/help-tooltip.js
Labels: Component: React, Component: UI, Status: PR > QA pass, Status: PR > Reviewed and Ready

#5819 Edit Pods QA, Part 5
  ui/js/blocks/pods-blocks-api.min.asset.json
  ui/js/blocks/pods-blocks-api.min.js
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list-item.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list-item.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/group-drag-layer.js
  ui/styles/dist/pods.css
  ui/styles/src/base/_admin.scss
  ui/styles/src/sourcemaps/pods.css.map
Labels: Component: React, Component: UI, Status: PR > QA pass, Status: PR > Reviewed and Ready
