Repository pods-framework/pods, pull requests merged in 2020-04, with the labels that each got.

#5681 Fix taxonomy option rewrite with front label tooltip
  classes/PodsAdmin.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge

#5672 Fix whitespace trimming for templates
  components/Templates/Templates.php
  includes/general.php
Labels: Component: Templates/Magic Tags, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5687 Allow input values compatible with the display format
  classes/fields/datetime.php
  tests/phpunit/includes/tests-pods-field-datetime.php
Labels: Focus: Back Compat, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug
