Repository pods-framework/pods, pull requests merged in 2020-05, with the labels that each got.

#5694 Add Block Creator JS
  jest-setup-wordpress-globals.js
  jest.config.json
  package.json
  ui/js/blocks/build/block-creator.min.js
  ui/js/blocks/src/blocks/README.md
  ui/js/blocks/src/blocks/components/BlockPreview.js
  ui/js/blocks/src/blocks/components/FieldInspectorControls.js
  ui/js/blocks/src/blocks/components/RenderedField.js
  ui/js/blocks/src/blocks/components/test/FieldInspectorControls.test.js
  ui/js/blocks/src/blocks/createAttributesFromFields.js
  ui/js/blocks/src/blocks/createBlockEditComponent.js
  ui/js/blocks/src/blocks/index.js
  ui/js/blocks/src/blocks/test/createBlockEditComponent.test.js
  ui/js/blocks/src/components/CheckboxGroup/README.md
  ui/js/blocks/src/components/CheckboxGroup/index.js
  ui/js/blocks/src/components/CheckboxGroup/styles.scss
  ui/js/blocks/src/components/NumberControl/README.md
  ui/js/blocks/src/components/NumberControl/index.js
  ui/js/blocks/src/config/html.js
  ui/js/blocks/src/editor.css
  ui/js/blocks/src/index.js
  ui/js/blocks/src/testData.js
  ui/js/blocks/src/utils/renderTemplate.js
  ui/js/blocks/src/utils/test/renderTemplate.test.js
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/pods-dfv.min.js.map
  webpack.common.js
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Feature

#5711 Set up eslint and fixes
  .babelrc
  .eslintrc.json
  classes/PodsInit.php
  package.json
  ui/js/blocks/build/block-creator.min.asset.json
  ui/js/blocks/build/block-creator.min.js
  ui/js/pods-dfv/pods-dfv.min.asset.json
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/src/admin/edit-pod/basic-options.js
  ui/js/pods-dfv/src/admin/edit-pod/edit-pod-name.js
  ui/js/pods-dfv/src/admin/edit-pod/edit-pod.js
  ui/js/pods-dfv/src/admin/edit-pod/handle-submit.js
  ui/js/pods-dfv/src/admin/edit-pod/main-tabs/active-tab-content.js
  ui/js/pods-dfv/src/admin/edit-pod/main-tabs/dynamic-tab-content.js
  ui/js/pods-dfv/src/admin/edit-pod/main-tabs/field-group-settings.js
  ui/js/pods-dfv/src/admin/edit-pod/main-tabs/field-group.js
  ui/js/pods-dfv/src/admin/edit-pod/main-tabs/field-groups.js
  ui/js/pods-dfv/src/admin/edit-pod/main-tabs/field-list.js
  ui/js/pods-dfv/src/admin/edit-pod/main-tabs/group-drag-layer.js
  ui/js/pods-dfv/src/admin/edit-pod/main-tabs/group-drag-source.js
  ui/js/pods-dfv/src/admin/edit-pod/main-tabs/group-drop-target.js
  ui/js/pods-dfv/src/admin/edit-pod/postbox.js
  ui/js/pods-dfv/src/admin/edit-pod/save-status-message.js
  ui/js/pods-dfv/src/admin/edit-pod/sluggable.js
  ui/js/pods-dfv/src/admin/edit-pod/store/actions.js
  ui/js/pods-dfv/src/admin/edit-pod/store/constants.js
  ui/js/pods-dfv/src/admin/edit-pod/store/reducer.js
  ui/js/pods-dfv/src/admin/edit-pod/store/selectors.js
  ui/js/pods-dfv/src/admin/edit-pod/store/state-paths.js
  ui/js/pods-dfv/src/admin/edit-pod/store/store.js
  ui/js/pods-dfv/src/admin/edit-pod/store/test/actions.js
  ui/js/pods-dfv/src/admin/edit-pod/store/test/reducer.js
  ui/js/pods-dfv/src/admin/edit-pod/store/test/selectors.js
  ui/js/pods-dfv/src/admin/edit-pod/store/test/store.js
  ui/js/pods-dfv/src/admin/edit-pod/with-drag-drop-context.js
  ui/js/pods-dfv/src/core/renderers/react-direct-renderer.js
  ui/js/pods-dfv/src/field-manifest.js
  webpack.common.js
Labels: Status: PR > Ready For Merge, Type: Enhancement

#5715 Manage Pod: Actions/info - fix name reloading
  ui/js/blocks/build/block-creator.min.asset.json
  ui/js/blocks/build/block-creator.min.js
  ui/js/pods-dfv/pods-dfv.min.asset.json
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/src/admin/edit-pod/postbox.js
  ui/js/pods-dfv/src/admin/edit-pod/store/constants.js
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5714 REST field options: Only display depth for array response type
  classes/PodsAdmin.php
Labels: Focus: Accessibility, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5700 Fix deprecated tax form actions
  classes/fields/pick.php
Labels: Focus: Deprecation, Status: PR > QA pass, Status: PR > Ready For Merge

#5673 WYSIWYG: Custom editor height
  classes/fields/wysiwyg.php
  ui/fields/tinymce.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5718 Manage Pod: Edit Pod Options/Edit Pod Slug
  .babelrc
  package.json
  ui/js/blocks/build/block-creator.min.asset.json
  ui/js/blocks/build/block-creator.min.js
  ui/js/pods-dfv/pods-dfv.min.asset.json
  ui/js/pods-dfv/pods-dfv.min.js
  ui/js/pods-dfv/src/admin/edit-pod/basic-options.js
  ui/js/pods-dfv/src/admin/edit-pod/edit-pod-name.js
  ui/js/pods-dfv/src/admin/edit-pod/edit-pod.js
  ui/js/pods-dfv/src/admin/edit-pod/main-tabs/active-tab-content.js
  ui/js/pods-dfv/src/admin/edit-pod/main-tabs/dynamic-tab-content.js
  ui/js/pods-dfv/src/admin/edit-pod/main-tabs/field-group.js
  ui/js/pods-dfv/src/admin/edit-pod/main-tabs/field-groups.js
  ui/js/pods-dfv/src/admin/edit-pod/postbox.js
  ui/js/pods-dfv/src/admin/edit-pod/sluggable.js
  ui/js/pods-dfv/src/admin/edit-pod/store/actions.js
  ui/js/pods-dfv/src/admin/edit-pod/store/constants.js
  ui/js/pods-dfv/src/admin/edit-pod/store/reducer.js
  ui/js/pods-dfv/src/admin/edit-pod/store/selectors.js
  ui/js/pods-dfv/src/admin/edit-pod/store/state-paths.js
  ui/js/pods-dfv/src/admin/edit-pod/store/store.js
  ui/js/pods-dfv/src/admin/edit-pod/store/test/actions.js
  ui/js/pods-dfv/src/admin/edit-pod/store/test/reducer.js
  ui/js/pods-dfv/src/admin/edit-pod/store/test/selectors-groups.js
  ui/js/pods-dfv/src/admin/edit-pod/store/test/selectors-options.js
  ui/js/pods-dfv/src/admin/edit-pod/store/test/selectors-podmeta.js
  ui/js/pods-dfv/src/admin/edit-pod/store/test/selectors-tabs.js
  ui/js/pods-dfv/src/admin/edit-pod/store/test/selectors-ui.js
  ui/js/pods-dfv/src/admin/edit-pod/store/test/selectors.js
  ui/js/pods-dfv/src/admin/edit-pod/store/test/store.js
  ui/js/pods-dfv/src/admin/edit-pod/store/testData.js
  ui/js/pods-dfv/src/components/dependent-field-option.js
  ui/js/pods-dfv/src/components/field-container.js
  ui/js/pods-dfv/src/components/field-option.js
  ui/js/pods-dfv/src/components/help-tooltip.js
  ui/js/pods-dfv/src/components/sluggable.js
  ui/js/pods-dfv/src/components/tabs/pods-nav-tab.js
  ui/js/pods-dfv/src/components/validation-messages.js
  ui/js/pods-dfv/src/core/renderers/mn-renderer.js
  ui/js/pods-dfv/src/core/renderers/react-direct-renderer.js
  ui/js/pods-dfv/src/core/renderers/react-renderer.js
  ui/js/pods-dfv/src/pods-dfv.js
Labels: Status: PR > QA pass, Status: PR > Ready For Merge

#5712 Only check `delete_users` for single installations
  includes/general.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5725 Manage fields & groups UI updates
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-groups.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-groups.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/manage-fields.scss
Labels: Component: DFV, Component: UI, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5726 Part of Manage Groups functionality
  package.json
  tests/js/dfv/file/models/file-upload-model.js
  tests/js/dfv/pick/models/relationship-model.js
  tests/js/dfv/pick/views/multiselect-selection-limits.js
  ui/js/blocks/pods-blocks-api.min.asset.json
  ui/js/blocks/pods-blocks-api.min.js
  ui/js/blocks/src/blocks/components/FieldInspectorControls.js
  ui/js/blocks/src/blocks/components/RenderedField.js
  ui/js/blocks/src/components/CheckboxControlExtended/index.js
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/edit-pod.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/active-tab-content.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/dynamic-tab-content.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group-settings.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-groups.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-groups.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/group-drag-layer.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/group-drag-source.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/manage-fields.scss
  ui/js/dfv/src/admin/edit-pod/postbox.js
  ui/js/dfv/src/admin/edit-pod/store/actions.js
  ui/js/dfv/src/admin/edit-pod/store/api-middleware.js
  ui/js/dfv/src/admin/edit-pod/store/constants.js
  ui/js/dfv/src/admin/edit-pod/store/reducer.js
  ui/js/dfv/src/admin/edit-pod/store/selectors.js
  ui/js/dfv/src/admin/edit-pod/store/state-paths.js
  ui/js/dfv/src/admin/edit-pod/store/store.js
  ui/js/dfv/src/admin/edit-pod/store/test/actions.js
  ui/js/dfv/src/admin/edit-pod/store/test/reducer.js
  ui/js/dfv/src/admin/edit-pod/store/test/selectors.js
  ui/js/dfv/src/admin/edit-pod/store/test/store.js
  ui/js/dfv/src/admin/edit-pod/store/testData.js
  ui/js/dfv/src/components/dependent-field-option.js
  ui/js/dfv/src/components/field-option.js
  ui/js/dfv/src/components/sluggable.js
  ui/js/dfv/src/helpers/sanitizeSlug.js
  ui/js/dfv/src/helpers/test/sanitizeSlug.js
  ui/js/dfv/src/pods-dfv.js
  ui/js/dfv/src/prop-types.js
  ui/styles/dist/pods.css
  ui/styles/src/base/_admin.scss
  ui/styles/src/sourcemaps/pods.css.map
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Feature

#5729 Feature/manage groups UI updates
  ui/js/blocks/pods-blocks-api.min.asset.json
  ui/js/blocks/pods-blocks-api.min.js
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-groups.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/manage-fields.scss
Labels: Component: CSS, Component: DFV, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement

#5727 Additional "Manage Groups" functionality
  ui/js/blocks/pods-blocks-api.min.asset.json
  ui/js/blocks/pods-blocks-api.min.js
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-groups.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-groups.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/group-drag-layer.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/group-drag-source.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/group-drop-target.js
  ui/js/dfv/src/admin/edit-pod/postbox.js
  ui/js/dfv/src/admin/edit-pod/save-status-message.js
  ui/js/dfv/src/admin/edit-pod/store/actions.js
  ui/js/dfv/src/admin/edit-pod/store/api-middleware.js
  ui/js/dfv/src/admin/edit-pod/store/constants.js
  ui/js/dfv/src/admin/edit-pod/store/reducer.js
  ui/js/dfv/src/admin/edit-pod/store/selectors.js
  ui/js/dfv/src/admin/edit-pod/store/state-paths.js
  ui/js/dfv/src/admin/edit-pod/store/store.js
  ui/js/dfv/src/admin/edit-pod/store/test/actions.js
  ui/js/dfv/src/admin/edit-pod/store/test/reducer.js
  ui/js/dfv/src/admin/edit-pod/store/test/selectors.js
  ui/js/dfv/src/admin/edit-pod/store/test/store.js
  ui/js/dfv/src/components/field-option.js
  ui/js/dfv/src/core/react/pods-dfv-prop-types.js
  ui/js/dfv/src/prop-types.js
Labels: Component: React, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Feature

#5730 Edit Group modal
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/edit-pod.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group-settings.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-groups.js
  ui/js/dfv/src/admin/edit-pod/store/actions.js
  ui/js/dfv/src/admin/edit-pod/store/constants.js
  ui/js/dfv/src/admin/edit-pod/store/reducer.js
  ui/js/dfv/src/admin/edit-pod/store/selectors.js
  ui/js/dfv/src/components/field-option.js
  ui/js/dfv/src/components/pods-nav-tab.js
  ui/js/dfv/src/prop-types.js
Labels: Component: React, Status: PR > QA pass, Status: PR > Ready For Merge

#5731 Feature/pod edit field group settings ui updates
  ui/js/blocks/pods-blocks-api.min.asset.json
  ui/js/blocks/pods-blocks-api.min.js
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/_edit-pod-variables.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group-settings.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group-settings.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-groups.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list.scss
  ui/js/dfv/src/admin/edit-pod/main-tabs/manage-fields.scss
Labels: Component: CSS, Component: React, Component: UI, Status: PR > QA pass, Status: PR > Ready For Merge, Type: Enhancement
