Repository pods-framework/pods, pull requests merged in 2020-10, with the labels that each got.

#5850 Fix selected query for autocomplete relationships
  classes/fields/pick.php
Labels: Component: DFV, Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Bug

#5841 Implement session_status() & pods_session_id()
  classes/PodsAPI.php
  classes/fields/file.php
  classes/fields/pick.php
  includes/general.php
  ui/admin/form-settings.php
  ui/admin/form.php
  ui/fields/attachment.php
  ui/front/form.php
Labels: Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Enhancement

#5853 Redirect to next Pod admin page if needed
  classes/PodsAdmin.php
Labels: Component: UI, Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Bug

#5533 Redo #5289: Enhance Pods auto-templates in general (especially Taxonomies and Comments)
  components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php
  components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Settings.php
Labels: Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Bug, Type: Enhancement

#5849 Do not limit users by user_status=0 anymore
  classes/PodsAPI.php
Labels: Component: Multisite, Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Bug

#5735 Make magic tags behave the same in various locations
  classes/Pods.php
  includes/data.php
  includes/general.php
Labels: Component: Templates/Magic Tags, Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Bug, Type: Enhancement

#5855 Fix/Enhance media each loops
  components/Templates/includes/functions-view_template.php
Labels: Component: Templates/Magic Tags, Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Bug, Type: Enhancement

#5816 Fix error if there is no prefix available
  classes/PodsData.php
Labels: Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Bug

#5813 use the new pods_evaluate_tags_sql() to prevent SQL errors on magic tags
  includes/data.php
  includes/general.php
  tests/phpunit/includes/tests-pods-data.php
Labels: Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Bug

#5802 Shortcode field template
  includes/general.php
Labels: Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Enhancement

#5854 Fix PDF src in each loop.
  classes/Pods.php
  includes/media.php
  tests/phpunit/includes/tests-media.php
Labels: Component: Templates/Magic Tags, Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Bug

#5861 Add correct i18n for select2/selectWoo
  classes/PodsI18n.php
  classes/PodsInit.php
  ui/js/pods-dfv/_src/pick/views/select-view.js
  ui/js/pods-dfv/pods-dfv.min.js
Labels: Focus: i18n, Status: PR > QA pass, Status: PR > Reviewed and Ready

#5811 Pods DFV compatibility for Page Builders
  classes/PodsI18n.php
  classes/PodsInit.php
Labels: Focus: Other Compatibility, Priority: Blocker, Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Bug

#5865 Fix empty filter: `pods_ignored_pick_objects`
  ui/admin/setup-edit-field.php
Labels: Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Bug

#5867 Prevent possible notice if image doesn't exist
  includes/media.php
Labels: Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Bug

#5844 DFV fields do not support HTML entities
  classes/fields/file.php
  classes/fields/pick.php
Labels: Priority: Blocker, Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Bug

#5870 Force avatar size + enhance support for custom sizes
  classes/Pods.php
  classes/fields/avatar.php
  includes/media.php
Labels: Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Bug

#5863 2.7.23 changelog
  readme.txt
Labels: Type: Release

#5872 Allow WP objects to be passed in `pods()`
  classes/Pods.php
  readme.txt
Labels: Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Enhancement
