Repository pods-framework/pods, pull requests merged in 2020-07, with the labels that each got.

#5763 Fix REST fields for media Pod
  classes/PodsRESTHandlers.php
Labels: Status: PR > QA pass, Status: PR > Ready For Merge, Type: Bug

#5777 Manage Pod Fixes
  ui/js/blocks/pods-blocks-api.min.asset.json
  ui/js/blocks/pods-blocks-api.min.js
  ui/js/blocks/src/config/html.js
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/edit-pod-name.js
  ui/js/dfv/src/admin/edit-pod/edit-pod.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/dynamic-tab-content.js
  ui/js/dfv/src/admin/edit-pod/store/actions.js
  ui/js/dfv/src/admin/edit-pod/store/test/actions.js
  ui/js/dfv/src/components/dependent-field-option.js
  ui/js/dfv/src/components/field-option.js
Labels: Component: React, Status: PR > QA pass, Status: PR > Ready For Merge

#5780 Manage Group QA updates
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/dynamic-tab-content.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-groups.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/settings-modal.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/settings-modal.scss
  ui/js/dfv/src/admin/edit-pod/store/actions.js
  ui/js/dfv/src/admin/edit-pod/store/constants.js
  ui/js/dfv/src/admin/edit-pod/store/reducer.js
  ui/js/dfv/src/admin/edit-pod/store/selectors.js
  ui/js/dfv/src/admin/edit-pod/store/state-paths.js
  ui/js/dfv/src/admin/edit-pod/store/test/actions.js
  ui/js/dfv/src/admin/edit-pod/store/test/reducer.js
  ui/js/dfv/src/components/dependent-field-option.js
  ui/js/dfv/src/components/field-option.js
  ui/js/dfv/src/prop-types.js
Labels: Component: React, Status: PR > QA pass, Status: PR > Ready For Merge

#5784 Manage Fields: Part 2
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list-item.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list.js
  ui/js/dfv/src/admin/edit-pod/store/actions.js
  ui/js/dfv/src/admin/edit-pod/store/test/actions.js
  ui/js/dfv/src/components/field-option.js
Labels: Component: React, Type: Feature
