Repository pods-framework/pods, pull requests merged in 2021-08, with the labels that each got.

#6069 Fix post type archive visibility
  classes/PodsInit.php
Labels: Status: PR > Pending Code Review, Status: PR > QA pass, Type: Bug

#6047 Fix Pod form - #5946
  classes/Pods.php
Labels: Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Bug

#6042 Support timezones for time fields
  classes/fields/datetime.php
Labels: Keyword: Needs Unit Tests, Status: PR > QA pass, Status: PR > Reviewed and Ready, Type: Bug

#6076 Release/2.7.29
  classes/PodsAdmin.php
  classes/PodsInit.php
  classes/PodsUI.php
  classes/fields/datetime.php
  classes/fields/file.php
  classes/fields/text.php
  includes/data.php
  includes/general.php
  init.php
  package.json
  readme.txt
  ui/front/form.php
  ui/images/arrow-right.png
  ui/images/arrow_complete.png
  ui/images/arrow_complete_previous.png
  ui/images/arrow_current.png
  ui/images/arrow_next.png
  ui/images/bullet_add.png
  ui/images/buttons.gif
  ui/images/calendar16.png
  ui/images/chosen-sprite.png
  ui/images/del.png
  ui/images/green-check.png
  ui/images/handle.gif
  ui/images/help.png
  ui/images/icon12.png
  ui/images/icon16.png
  ui/images/icon24.png
  ui/images/icon32.png
  ui/images/logo_backupbuddy.png
  ui/images/logo_vaultpress.png
  ui/images/page_white_edit.png
  ui/images/pods-logo-hoz-rgb.png
  ui/images/pods-logo-notext-rgb-transparent.png
  ui/images/pods-logo-notext-rgb.png
  ui/images/red-x.png
  ui/images/smoothness/ui-bg_flat_0_aaaaaa_40x100.png
  ui/images/smoothness/ui-bg_flat_75_ffffff_40x100.png
  ui/images/smoothness/ui-bg_glass_55_fbf9ee_1x400.png
  ui/images/smoothness/ui-bg_glass_65_ffffff_1x400.png
  ui/images/smoothness/ui-bg_glass_75_dadada_1x400.png
  ui/images/smoothness/ui-bg_glass_75_e6e6e6_1x400.png
  ui/images/smoothness/ui-bg_glass_95_fef1ec_1x400.png
  ui/images/smoothness/ui-bg_highlight-soft_75_cccccc_1x100.png
  ui/images/smoothness/ui-icons_222222_256x240.png
  ui/images/smoothness/ui-icons_2e83ff_256x240.png
  ui/images/smoothness/ui-icons_454545_256x240.png
  ui/images/smoothness/ui-icons_888888_256x240.png
  ui/images/smoothness/ui-icons_cd0a0a_256x240.png
  ui/images/spinner.gif
  ui/images/tick.png
  ui/js/cleditor/images/buttons.gif
  ui/js/cleditor/images/toolbar.gif
  ui/styles/dist/pods.css
  ui/styles/src/base/_admin.scss
Labels: Type: Release

#6080 Pods 2.7.30
  classes/PodsInit.php
  classes/PodsMeta.php
  classes/fields/avatar.php
  components/Templates/class-pods_templates.php
  init.php
  package.json
  readme.txt
Labels: Type: Release

#5626 Disable sessions by default
  classes/Pods.php
  classes/PodsAdmin.php
  classes/PodsInit.php
  includes/general.php
  src/Pods/Admin/Service_Provider.php
  src/Pods/Admin/Settings.php
  ui/admin/settings-settings.php
  ui/admin/settings.php
  ui/forms/div-rows.php
  ui/forms/list-rows.php
  ui/forms/p-rows.php
  ui/forms/table-rows.php
Labels: Type: Enhancement, Keyword: Focus, Status: In Progress

#4099 Pods Multisite query support - add `blog_id` parameter
  includes/general.php
Labels: Type: Enhancement, Status: PR > Reviewed and Ready
