Repository pods-framework/pods, pull requests merged in 2021-11, with the labels that each got.

#6288 Bugfix: REST API field settings
  classes/PodsRESTFields.php
Labels: Type: Bug, Keywords: Regression, Component: REST API, Status: PR > QA pass

#6286 Bugfix i18n integration
  src/Pods/Integrations/Polylang.php
  src/Pods/Integrations/WPML.php
Labels: Focus: i18n, Keywords: Regression, Status: PR > QA pass

#6267 i18n component v1.1 - translate Whatsit args
  components/I18n/I18n.php
  src/Pods/Whatsit.php
Labels: Type: Bug, Type: Enhancement, Focus: i18n, Status: PR > QA pass

#6278 Customize Pick field label "Add New"
  classes/fields/pick.php
  ui/js/dfv/src/config/prop-types.js
  ui/js/dfv/src/fields/pick/index.js
Labels: Type: Enhancement, Component: UI, Component: DFV

#6276 Customize Color field labels
  classes/fields/color.php
  ui/js/dfv/src/config/prop-types.js
  ui/js/dfv/src/fields/color/index.js
Labels: Type: Enhancement, Component: UI, Component: DFV

#6305 Fixes for pods_group_add() basic handling
  classes/PodsMeta.php
  includes/general.php
  init.php
  readme.txt
Labels: Type: Release

#6311 Pods 2.8.5
  classes/PodsAPI.php
  classes/PodsInit.php
  init.php
  package.json
  readme.txt
  src/Pods/Whatsit/Pod.php
Labels: Type: Release

#6335 Fix i18n loop since 2.8.6
  classes/PodsI18n.php
Labels: Type: Bug, Priority: Blocker, Status: PR > Pending Code Review, Status: PR > QA pending

#6323 Pods 2.8.6
  classes/PodsAPI.php
  classes/PodsAdmin.php
  classes/PodsField.php
  classes/PodsI18n.php
  classes/PodsInit.php
  classes/PodsMeta.php
  classes/PodsRESTHandlers.php
  classes/PodsUI.php
  classes/fields/boolean.php
  classes/fields/code.php
  classes/fields/color.php
  classes/fields/datetime.php
  classes/fields/email.php
  classes/fields/file.php
  classes/fields/link.php
  classes/fields/number.php
  classes/fields/oembed.php
  classes/fields/paragraph.php
  classes/fields/password.php
  classes/fields/phone.php
  classes/fields/pick.php
  classes/fields/slug.php
  classes/fields/text.php
  classes/fields/website.php
  classes/fields/wysiwyg.php
  components/Migrate-Packages/Migrate-Packages.php
  components/Templates/includes/functions-view_template.php
  includes/forms.php
  includes/general.php
  init.php
  package.json
  readme.txt
  src/Pods/Admin/Config/Field.php
  src/Pods/Whatsit/Field.php
  tests/codeception/wpunit/Pods/Shortcode/PodsTest.php
  ui/admin/callouts/friends_2021_29.php
  ui/admin/settings-settings.php
  ui/admin/view.php
  ui/fields/_comment.php
  ui/fields/_label.php
  ui/fields/attachment.php
  ui/fields/cleditor.php
  ui/fields/codemirror.php
  ui/fields/currency.php
  ui/fields/datetime.php
  ui/fields/link.php
  ui/fields/slider.php
  ui/forms/form.php
  ui/front/form.php
  ui/front/view.php
  ui/js/blocks/block-types/pods-block-field/block.json
  ui/js/blocks/block-types/pods-block-form/block.json
  ui/js/blocks/block-types/pods-block-list/block.json
  ui/js/blocks/block-types/pods-block-single/block.json
  ui/js/blocks/block-types/pods-block-view/block.json
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/fields/datetime/datetime.scss
  ui/styles/dist/pods-form.css
  ui/styles/src/base/_form.scss
Labels: Type: Release
