Repository pods-framework/pods, pull requests merged in 2021-12, with the labels that each got.

#6339 Pods 2.8.6.1
  includes/general.php
  init.php
  readme.txt
Labels: Type: Release

#6269 Fix number formatting
  classes/fields/number.php
  ui/fields/number.php
Labels: Type: Bug, Keywords: Regression, Status: PR > Pending Code Review, Status: PR > QA pass

#6346 Pods 2.8.8
  classes/Pods.php
  classes/PodsAPI.php
  classes/PodsInit.php
  classes/PodsMeta.php
  classes/fields/number.php
  classes/fields/pick.php
  components/Pages.php
  components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php
  components/Templates/includes/functions-view_template.php
  includes/forms.php
  includes/media.php
  init.php
  package.json
  readme.txt
  src/Pods/Admin/Config/Pod.php
  src/Pods/Blocks/Types/Base.php
  src/Pods/Blocks/Types/Field.php
  src/Pods/Blocks/Types/Form.php
  src/Pods/Blocks/Types/Item_List.php
  src/Pods/Blocks/Types/Item_Single.php
  src/Pods/Blocks/Types/View.php
  src/Pods/Integrations/Polylang.php
  src/Pods/Whatsit/Pod.php
  ui/admin/setup-add.php
  ui/fields/number.php
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/config/prop-types.js
  ui/js/dfv/src/fields/pick/index.js
Labels: Type: Release

#6359 Wrong usage of is_type_covered(), should do the opposite
  ui/admin/setup-add.php
Labels: Type: Bug, Priority: Blocker, Keywords: Regression, Status: PR > Pending Code Review, Status: PR > QA pending

#6361 Fix formats in slider UI
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/fields/currency/index.js
  ui/js/dfv/src/fields/number-field/index.js
Labels: Type: Bug, Keywords: Regression, Status: PR > Pending Code Review, Status: PR > QA pass

#6365 Overwrite WP core max values and set same offset as media modal.
  ui/js/dfv/src/components/iframe-modal.scss
Labels: Type: Enhancement, Component: UI, Component: CSS
