Repository pods-framework/pods, pull requests merged in 2021-01, with the labels that each got.

#5911 Add pods_shortcode_detect_from_current_post filter for more flexibility
  includes/general.php
Labels: Type: Enhancement

#5915 Fix php error
  components/Templates/includes/element-pod_reference.php
Labels: Status: PR > Pending Code Review, Status: PR > QA pass, Type: Bug

#5912 Pods 2.7.26 release
  components/Templates/includes/element-pod_reference.php
  includes/general.php
  init.php
  package.json
  readme.txt
Labels: Type: Release
