Repository pods-framework/pods, pull requests merged in 2021-09, with the labels that each got.

#6110 More DFV fixes
  classes/PodsAPI.php
  classes/PodsField.php
  classes/PodsForm.php
  classes/PodsMeta.php
  package-lock.json
  package.json
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/edit-pod.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/active-tab-content.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-group.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-groups.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list-item.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/field-list.js
  ui/js/dfv/src/admin/edit-pod/postbox.js
  ui/js/dfv/src/admin/edit-pod/save-status-message.js
  ui/js/dfv/src/components/connected-field-wrapper.js
  ui/js/dfv/src/config/prop-types.js
  ui/js/dfv/src/core/pods-dfv-app.js
  ui/js/dfv/src/fields/boolean-group/boolean-group-subfield.js
  ui/js/dfv/src/fields/boolean/index.js
  ui/js/dfv/src/fields/boolean/test/index.js
  ui/js/dfv/src/fields/file/index.js
  ui/js/dfv/src/fields/pick/checkbox-select.js
  ui/js/dfv/src/fields/pick/index.js
  ui/js/dfv/src/fields/pick/radio-select.js
  ui/js/dfv/src/fields/pick/simple-select.js
  ui/js/dfv/src/pods-dfv.js
  ui/js/dfv/src/store/store.js
  ui/js/dfv/src/store/test/store.js
Labels: Type: Bug, Status: In Progress, Component: DFV, Status: PR > QA fail, Component: React

#6125 Improvements to "Edit Pod" modals
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/settings-modal.js
  ui/js/dfv/src/admin/edit-pod/main-tabs/settings-modal.scss
Labels: Component: UI, Component: React

#6147 Improve Plupload item context
  classes/fields/file.php
Labels: Type: Bug, Type: Enhancement, Status: PR > Reviewed and Ready, Status: PR > QA pending

#6149 Pods 2.8: Enhance getting Pod WhatsIt translations
  components/I18n/I18n.php
Labels: Type: Enhancement, Status: PR > Pending Code Review, Status: PR > QA pass
