Repository pods-framework/pods, pull requests merged in 2022-08, with the labels that each got.

#6578 Support webp as default image extension
  classes/fields/file.php
Labels: Type: Enhancement, Status: PR > Reviewed and Ready, Status: PR > QA pending

#6562 Feature/6561 performance
  src/Pods/Whatsit/Storage/Post_Type.php
Labels: Focus: Performance, Status: PR > Pending Code Review, Status: PR > QA pending

#6584 CodeMirror fix
  package-lock.json
  package.json
  ui/js/blocks/pods-blocks-api.min.asset.json
  ui/js/blocks/pods-blocks-api.min.js
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/fields/code/index.js
Labels: Status: PR > Reviewed and Ready, Component: DFV, Status: PR > QA pass

#6585 Pods 2.9.1
  classes/PodsAdmin.php
  components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Settings.php
  init.php
  package-lock.json
  package.json
  readme.txt
  src/Pods/Config_Handler.php
  ui/admin/callouts/friends_2022_30.php
  ui/js/blocks/pods-blocks-api.min.asset.json
  ui/js/blocks/pods-blocks-api.min.js
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/fields/code/index.js
Labels: Type: Release

#6859 Color picker popover UI
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/fields/color/color.scss
  ui/js/dfv/src/fields/color/index.js
Labels: Type: Enhancement, Component: UI, Status: PR > Pending Code Review, Status: PR > QA pending, Component: React

#6854 Improve repeatable UI
  classes/PodsAPI.php
  ui/js/dfv/src/fields/color/color.scss
  ui/js/dfv/src/fields/color/index.js
Labels: Component: UI, Status: PR > Pending Code Review, Status: PR > QA pending, Component: React

#6866 Pods 2.9.2
  classes/PodsAPI.php
  classes/PodsInit.php
  classes/fields/datetime.php
  classes/fields/file.php
  init.php
  package.json
  readme.txt
  src/Pods/Admin/Config/Field.php
  src/Pods/Pod_Manager.php
  tests/codeception/_data/kitchen-sink-readonly-package.json
  ui/js/blocks/pods-blocks-api.min.asset.json
  ui/js/blocks/pods-blocks-api.min.js
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/components/field-wrapper/field-wrapper.scss
  ui/js/dfv/src/fields/color/color.scss
  ui/js/dfv/src/fields/color/index.js
  ui/js/dfv/src/fields/datetime/datetime.scss
  ui/js/dfv/src/fields/datetime/index.js
Labels: Type: Release

#6872 Pods 2.9.3
  classes/PodsForm.php
  classes/fields/wysiwyg.php
  init.php
  package-lock.json
  package.json
  readme.txt
  src/Pods/Pod_Manager.php
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
Labels: Type: Release
