Repository pods-framework/pods, pull requests merged in 2022-04, with the labels that each got.

#6490 Fix term autotemplates
  components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php
Labels: Type: Bug, Status: PR > Pending Code Review, Component: Templates/Magic Tags, Status: PR > QA pass

#6495 Pods 2.8.14
  classes/Pods.php
  classes/PodsAPI.php
  classes/PodsData.php
  classes/PodsView.php
  classes/fields/datetime.php
  components/Pages.php
  includes/data.php
  includes/general.php
  init.php
  package.json
  readme.txt
  src/Pods/REST/V1/Endpoints/Base.php
  src/Pods/REST/V1/Endpoints/Field.php
  src/Pods/REST/V1/Endpoints/Field_Slug.php
  src/Pods/REST/V1/Endpoints/Group.php
  src/Pods/REST/V1/Endpoints/Group_Slug.php
  src/Pods/REST/V1/Endpoints/Pod.php
  src/Pods/REST/V1/Endpoints/Pod_Slug.php
  src/Pods/REST/V1/Service_Provider.php
  src/Pods/REST/V1/Validator/Base.php
Labels: Type: Release

#6497 Pods 2.8.15
  classes/Pods.php
  classes/PodsData.php
  classes/fields/pick.php
  init.php
  package.json
  readme.txt
  src/Pods/REST/V1/Endpoints/Base.php
Labels: Type: Release

#6498 Fix for multi-select fields having values imploded when saved on older ajax forms
  ui/js/jquery.pods.js
Labels: Type: Bug, Status: PR > Reviewed and Ready, Component: Frontend Forms, Status: PR > QA pass
