Repository pods-framework/pods, pull requests merged in 2022-02, with the labels that each got.

#6433 Release/2.8.10
  classes/PodsAPI.php
  includes/general.php
  init.php
  package.json
  readme.txt
  src/Pods/Admin/Settings.php
Labels: Type: Release

#6458 Build process updates for 2.8.x
  .babelrc
  .github/workflows/auto-build.yml
  .github/workflows/tests-js.yml
  .nvmrc
  jest-setup-wordpress-globals.js
  jest.config.js
  jest.config.json
  package-lock.json
  package.json
  ui/js/blocks/pods-blocks-api.min.asset.json
  ui/js/blocks/pods-blocks-api.min.js
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/styles/src/base/_wizard.scss
  ui/styles/src/helpers/_mixins.scss
  ui/styles/src/pods-form.css
  ui/styles/src/pods-form.css.map
  ui/styles/src/pods-wizard.css
  ui/styles/src/pods-wizard.css.map
  ui/styles/src/pods.css
  ui/styles/src/pods.css.map
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: Type: Enhancement, Component: React

#6449 Refresh language cache after WPML has switch language.
  src/Pods/Integrations/WPML.php
Labels: Type: Bug, Focus: i18n, Focus: Other Compatibility, Status: PR > Pending Code Review, Status: PR > QA pass
