Repository pods-framework/pods, pull requests merged in 2023-06, with the labels that each got.

#7095 Fetch object ID from WP object
  classes/Pods.php
Labels: Type: Enhancement, Status: PR > Pending Code Review, Status: PR > QA pending

#7093 Pods 2.9.16
  changelog.txt
  classes/Pods.php
  classes/PodsAPI.php
  classes/PodsAdmin.php
  classes/fields/wysiwyg.php
  includes/general.php
  init.php
  package.json
  readme.txt
  src/Pods/Tools/Repair.php
  src/Pods/Whatsit.php
  src/Pods/Whatsit/Pod.php
  ui/admin/setup-edit.php
Labels: Type: Release

#7102 Pods 2.9.17
  changelog.txt
  classes/PodsAPI.php
  classes/PodsAdmin.php
  classes/PodsForm.php
  classes/PodsMeta.php
  includes/general.php
  init.php
  package.json
  readme.txt
  src/Pods/Admin/Settings.php
  src/Pods/REST/V1/Endpoints/Pods.php
  src/Pods/Tools/Repair.php
  src/Pods/Whatsit.php
  src/Pods/Whatsit/Group.php
  src/Pods/Whatsit/Pod.php
  src/Pods/Whatsit/Storage/Post_Type.php
  src/Pods/Wisdom_Tracker.php
  ui/admin/setup-add.php
Labels: Type: Release

#7106 HOTFIX: Compatibility with tribe service provider
  changelog.txt
  classes/PodsInit.php
  includes/general.php
  init.php
  package.json
  readme.txt
  src/Pods/Admin/Service_Provider.php
  src/Pods/Blocks/Service_Provider.php
  src/Pods/CLI/Service_Provider.php
  src/Pods/Integrations/Service_Provider.php
  src/Pods/Integrations/WPGraphQL/Service_Provider.php
  src/Pods/REST/V1/Service_Provider.php
  src/Pods/Service_Provider.php
  src/Pods/Service_Provider_Base.php
  src/Pods/Service_Provider_Fallback.php
Labels: Type: Bug, Priority: Blocker, Focus: Other Compatibility, Status: PR > Pending Code Review, Status: PR > QA pending

#7108 Abstract DFV API and start abstracting config handling
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/core/api.js
  ui/js/dfv/src/core/app.js
  ui/js/dfv/src/pods-dfv.js
Labels: Component: DFV

#7114 Pods 2.9.19
  changelog.txt
  classes/PodsView.php
  init.php
  package.json
  readme.txt
Labels: Type: Release
