Repository pods-framework/pods, pull requests merged in 2023-09, with the labels that each got.

#7149 Support itemdata collections for select
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/fields/pick/index.js
  ui/js/dfv/src/fields/pick/simple-select.js
Labels: Type: Bug, Status: PR > Pending Code Review, Status: PR > QA pending, Component: React

#7143 Relationship field: Fix return data when value exists + Allow -1 as limit
  classes/fields/pick.php
Labels: Type: Bug, Keywords: Regression, Status: PR > Pending Code Review, Status: PR > QA pending

#7142 Run post/page ID through pods_v to trigger filters
  includes/general.php
Labels: Focus: i18n, Keywords: Regression, Status: PR > Pending Code Review, Status: PR > QA pass

#7140 Use new get_tax_prop method with backwards compatibility
  src/Pods/Integrations/Polylang.php
Labels: Focus: i18n, Status: In Progress, Status: PR > Pending Code Review, Status: PR > QA pending

#7125 Improve tiles UI
  ui/styles/dist/pods-form.css
  ui/styles/dist/pods.css
  ui/styles/src/base/_dfv-list.scss
Labels: Component: UI, Status: PR > Pending Code Review, Status: PR > QA pass

#7146 Fix deprecated PHP
  classes/PodsUI.php
  components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php
  components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Settings.php
Labels: Type: Bug, Status: PR > Pending Code Review, Status: PR > QA pending

#7119 fix: form ui label tooltip heading and anchor color contract (#7118)
  components/Templates/Templates.php
  ui/styles/src/base/_wizard.scss
  ui/styles/src/libs/_jquery-qtip.scss
Labels: Type: Bug, Component: UI, Component: CSS

#7164 Pods 3.0.1
  changelog.txt
  init.php
  package.json
  readme.txt
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/core/api.js
Labels: Type: Release

#7174 Pods 3.0.2
  changelog.txt
  classes/Pods.php
  classes/PodsAPI.php
  classes/PodsAdmin.php
  classes/PodsData.php
  classes/PodsInit.php
  classes/PodsUI.php
  classes/fields/pick.php
  components/Templates/includes/functions-pod_reference.php
  components/Templates/includes/functions-view_template.php
  init.php
  package.json
  readme.txt
  src/Pods/Admin/Config/Pod.php
  src/Pods/Blocks/Types/Base.php
  src/Pods/Config_Handler.php
  src/Pods/Whatsit/Field.php
  src/Pods/Whatsit/Storage/Post_Type.php
  src/Pods/Whatsit/Store.php
  ui/admin/callouts/friends_2023_docs.php
  ui/admin/view.php
  ui/forms/form.php
  ui/forms/type/post.php
  ui/js/dfv/pods-dfv.min.asset.json
  ui/js/dfv/pods-dfv.min.js
  ui/js/dfv/src/fields/pick/full-select.js
Labels: Type: Release

#7178 Pods 3.0.3
  changelog.txt
  classes/Pods.php
  classes/PodsAPI.php
  init.php
  package.json
  readme.txt
Labels: Type: Release

#7180 Pods 3.0.4
  changelog.txt
  classes/PodsAPI.php
  classes/fields/pick.php
  init.php
  package.json
  readme.txt
  src/Pods/Data/Conditional_Logic.php
  src/Pods/Tools/Repair.php
  src/Pods/Whatsit.php
  src/Pods/Whatsit/Block_Field.php
  src/Pods/Whatsit/Field.php
  src/Pods/Whatsit/Group.php
  src/Pods/Whatsit/Legacy_Object.php
  src/Pods/Whatsit/Pod.php
  ui/admin/settings-tools.php
Labels: Type: Release

#7184 Include full image size in reference list
  components/Templates/includes/functions-pod_reference.php
Labels: Type: Enhancement, Status: PR > Pending Code Review, Status: PR > QA pass

#7185 Use prefix instead of parsing our own
  classes/fields/pick.php
Labels: Type: Bug, Focus: Other Compatibility, Status: PR > Pending Code Review, Status: PR > QA pending
